export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM'
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM'
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM

export const CHANGE_FLAG = 'CHANGE_FLAG'
export type CHANGE_FLAG = typeof CHANGE_FLAG

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
console.log(DECREMENT_ENTHUSIASM, 'CHANGE_LANGUAGE')
export type CHANGE_LANGUAGE = typeof CHANGE_LANGUAGE